# Generated by Django 4.0.3 on 2022-05-07 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_foodcourt_alter_customer_state_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodcourt',
            old_name='brand',
            new_name='resturant',
        ),
    ]
