# Generated by Django 4.0.3 on 2022-05-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_brand_foodcourt_resturant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcourt',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
