# Generated by Django 4.0.3 on 2022-05-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_foodcourt_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcourt',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
