# Generated by Django 4.0.3 on 2022-05-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_foodcourt_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodCourt',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('TW', 'Top Wear'), ('BW', 'Bottom Wear'), ('EL', 'Electronics'), ('GE', 'Gym'), ('HA', 'House Appliances'), ('MS', 'Medical Store'), ('RM', 'Raw Materials'), ('JL', 'Jewellery'), ('TS', 'Toys'), ('PD', 'PinDrives'), ('FD', 'Fridge'), ('KB', 'Keyboard'), ('PE', 'Printer'), ('CL', 'Cooler'), ('TB', 'Teddy'), ('BC', 'Cycle'), ('TT', 'Train'), ('PT', 'Plain'), ('BT', 'Barbie'), ('DT', 'Doll'), ('BJ', 'Bangles'), ('EJ', 'Ear-Rings'), ('NJ', 'Necklace'), ('RJ', 'Rings'), ('JB', 'Bracelets'), ('BR', 'Broaches'), ('NP', 'Nose Pin'), ('BRR', 'Briyani')], max_length=5),
        ),
    ]
