# Generated by Django 4.0.3 on 2022-05-10 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=126)),
                ('profile', models.ImageField(upload_to='homeServices')),
                ('mobile', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=126)),
                ('category', models.CharField(choices=[('Plumber', 'Plumber'), ('Electrician', 'Electrician'), ('Carpentry', 'Carpentry'), ('Welder', 'Welder'), ('Saloon', 'Saloon'), ('Tailor', 'Tailor')], max_length=120)),
                ('experience', models.IntegerField(max_length=12)),
                ('proof', models.ImageField(upload_to='homeServices')),
            ],
        ),
        migrations.CreateModel(
            name='HotelRooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=126)),
                ('room', models.ImageField(upload_to='hotelRooms')),
                ('mobile', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=126)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room'), ('5 Star Deluex', '5 Star Deluex'), ('Family Type Room', 'Family Type Room'), ('Studio Room', 'Studio Room')], max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=26)),
                ('days', models.IntegerField(max_length=12)),
                ('hours', models.IntegerField(max_length=12)),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.homeservices')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomsCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=26)),
                ('days', models.IntegerField(max_length=12)),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hotelrooms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HotelRoomsOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='Pending', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hotelrooms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HomeServicesOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='Pending', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.homeservices')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
