# Generated by Django 4.0.3 on 2022-05-10 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_seat_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
