# Generated by Django 4.0.3 on 2022-05-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='directorName',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
