# Generated by Django 4.0.3 on 2022-05-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_movie_directorname'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='releaseDate',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
