# Generated by Django 4.0.3 on 2022-05-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_traindetail_availableon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traindetail',
            name='availableOn',
            field=models.DateField(),
        ),
    ]
