# Generated by Django 4.0.3 on 2022-05-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_traindetail_availableon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traindetail',
            name='toCity',
            field=models.CharField(choices=[('AC', 'AC'), ('NON-AC', 'NON-AC')], max_length=500),
        ),
    ]
