# Generated by Django 4.0.3 on 2022-05-11 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_flightdetail_flightcart_flightbooked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movieType',
        ),
    ]
