# Generated by Django 4.0.3 on 2022-05-11 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_movie_movietype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightdetail',
            name='seat_type',
        ),
    ]
