# Generated by Django 4.0.3 on 2022-05-11 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_flightdetail_seat_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightdetail',
            name='distance',
        ),
    ]
