# Generated by Django 4.0.3 on 2022-05-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_busdetail_alter_flightbooked_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdetail',
            name='trainNumber',
            field=models.CharField(max_length=20),
        ),
    ]
