# Generated by Django 4.0.3 on 2022-05-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_busdetail_trainnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movieType',
            field=models.CharField(choices=[('Thriller', 'Thriller')], default=1, max_length=120),
            preserve_default=False,
        ),
    ]
