# Generated by Django 4.0.3 on 2022-04-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_category_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('TW', 'Top Wear'), ('BW', 'Bottom Wear'), ('EL', 'Electronics'), ('GE', 'Gym'), ('HA', 'House Appliances'), ('MS', 'Medical Store'), ('RM', 'Raw Materials'), ('JL', 'Jewellery'), ('TS', 'Toys'), ('PD', 'PinDrives'), ('FD', 'Fridge')], max_length=2),
        ),
    ]
