from multiprocessing import AuthenticationError
from re import template
from django.conf import settings
from django.urls import path
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from .forms import LoginForm, MyPasswordChangeForm, MyPasswordResetForm, MySetPasswordForm
from app import views
from app.forms import LoginForm
urlpatterns = [
    path('',views.ProductView.as_view(),name="home"),
    path('product-detail/<int:pk>', views.ProductDetailView.as_view(), name='product-detail'),
    path('add-to-cart/', views.add_to_cart, name='add-to-cart'),
    path('cart/',views.show_cart,name='showcart'),
    path('pluscart/',views.plus_cart,name='pluscart'),
    path('minuscart/',views.minus_cart,name='minuscart'),
    path('removecart/',views.remove_cart,name='removecart'),
    # path('buy/', views.buy_now, name='buy-now'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('address/', views.address, name='address'),
    path('orders/', views.orders, name='orders'),
    path('mobile/', views.mobile, name='mobile'),
    path('mobile/<slug:data>', views.mobile, name='mobiledata'),
    path('monitors/', views.monitors_view, name='monitors'),
    path('monitors/<slug:data>', views.monitors_view, name='monitorsdata'),
    path('computers/', views.computers_view, name='computers'),
    path('computers/<slug:data>', views.computers_view, name='computersdata'),
    path('printer/', views.printers_view, name='printer'),
    path('printer/<slug:data>', views.printers_view, name='printerdata'),
    path('speaker/', views.speckers_view, name='speaker'),
    path('speaker/<slug:data>', views.speckers_view, name='speakerdata'),
    path('cooler/', views.cooler_view, name='cooler'),
    path('cooler/<slug:data>', views.cooler_view, name='coolerdata'),
    path('AC/', views.AC_view, name='AC'),
    path('AC/<slug:data>', views.AC_view, name='ACdata'),
    path('fridge/', views.Fridge_view, name='fridge'),
    path('fridge/<slug:data>', views.Fridge_view, name='fridgedata'),
    # path('login/', views.login, name='login'),
    path('accounts/login/',auth_views.LoginView.as_view(template_name='app/login.html',authentication_form=LoginForm),name='login'),
    path('logout/',auth_views.LogoutView.as_view(next_page='login'),name='logout'),
    path('changepassword/',auth_views.PasswordChangeView.as_view(template_name='app/passwordchange.html',form_class=MyPasswordChangeForm,success_url='/passwordchangedone/'),name='passwordchange'),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='app/password_reset.html',form_class=MyPasswordResetForm),name='password_reset'),
    path('password-reset-done/',auth_views.PasswordChangeDoneView.as_view(template_name='app/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='app/password_reset_confirm.html',form_class=MySetPasswordForm),name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='app/password_reset_complete.html'),name='password_reset_complete'),
    path('passwordchangedone/',auth_views.PasswordResetDoneView.as_view(template_name='app/passwordchangedone.html'),name='passwordchangedone'),
    path('registration/', views.CustomerRegistrationView.as_view(), name='customerregistration'),
    path('checkout/', views.checkout, name='checkout'),
    path('paymentdone/', views.payment_done, name='paymentdone'),
    path('bicycle/', views.bicycle_view, name='bicycle'),
    path('bicycle/<slug:data>', views.bicycle_view, name='bicycledata'),
    path('train/', views.trains_view, name='train'),
    path('train/<slug:data>', views.trains_view, name='traindata'),
    path('dolls/', views.dolls_view, name='doll'),
    path('dolls/<slug:data>', views.dolls_view, name='dolldata'),
    path('laptop/', views.laptops_view, name='laptop'),
    path('laptop/<slug:data>', views.laptops_view, name='laptopdata'),
    path('bear/', views.bear_view, name='bear'),
    path('bear/<slug:data>', views.bear_view, name='beardata'),
    path('plain/', views.plain_view, name='plain'),
    path('plain/<slug:data>', views.plain_view, name='plaindata'),
    path('bangles/', views.bangles_view, name='bangles'),
    path('bangles/<slug:data>', views.bangles_view, name='banglesdata'),
    path('earrings/', views.rings_view, name='earrings'),
    path('earrings/<slug:data>', views.rings_view, name='earringsdata'),
    path('rings/', views.earRings_view, name='rings'),
    path('rings/<slug:data>', views.earRings_view, name='ringsdata'),
    path('necklace/', views.necklace_view, name='necklace'),
    path('necklace/<slug:data>', views.necklace_view, name='necklacedata'),
    path('broochs/', views.broochs_view, name='broochs'),
    path('broochs/<slug:data>', views.broochs_view, name='broochsdata'),
    path('nosepin/', views.nosepin_view, name='nosepin'),
    path('nosepin/<slug:data>', views.nosepin_view, name='nosepindata'),
    path('bellypin/', views.bellypin_view, name='bellypin'),
    path('bellypin/<slug:data>', views.bellypin_view, name='bellypindata'),
    path('chains/', views.chains_view, name='chains'),
    path('chains/<slug:data>', views.chains_view, name='chainsdata'),
    path('bracelate/', views.bracelate_view, name='bracelate'),
    path('bracelate/<slug:data>', views.bracelate_view, name='bracelatedata'),
    path('sarees/', views.sarees_view, name='sarees'),
    path('sarees/<slug:data>', views.sarees_view, name='sareesdata'),
    path('kurtis/', views.kurtis_view, name='kurtis'), 
    path('kurtis/<slug:data>', views.kurtis_view, name='kurtisdata'),
    path('western/', views.western_view, name='western'), 
    path('western/<slug:data>', views.western_view, name='westerndata'),
    path('suits/', views.suits_view, name='suits'), 
    path('suits/<slug:data>', views.suits_view, name='suitsdata'),
    path('ethinic/', views.ethinic_view, name='ethinic'), 
    path('ethinic/<slug:data>', views.ethinic_view, name='ethinicdata'),
    path('womenAss/', views.womenAss_view, name='womenAss'), 
    path('womenAss/<slug:data>', views.womenAss_view, name='womenAssdata'),
    path('tshirts/', views.menTshirt_view, name='tshirts'), 
    path('tshirts/<slug:data>', views.menTshirt_view, name='tshirtsdata'),
    path('shirts/', views.menshirt_view, name='shirts'), 
    path('shirts/<slug:data>', views.menshirt_view, name='shirtsdata'),
    path('jeans/', views.jeans_view, name='jeans'), 
    path('jeans/<slug:data>', views.jeans_view, name='jeansdata'),
    path('party/', views.partyWear_view, name='party'), 
    path('party/<slug:data>', views.partyWear_view, name='partydata'),
    path('night/', views.nightWear_view, name='night'), 
    path('night/<slug:data>', views.nightWear_view, name='nightdata'),
    path('menAss/', views.mesAss_view, name='menAss'), 
    path('menAss/<slug:data>', views.mesAss_view, name='menAssdata'),
    path('grocery/', views.grocery_counter, name='grocery'), 
    path('grocery/<slug:data>', views.grocery_counter, name='grocerydata'),
    path('gym/', views.gym_view, name='gym'), 
    path('gym/<slug:data>', views.gym_view, name='gymdata'),
    path('furtinure/', views.furtinures_View, name='furtinure'), 
    path('furtinure/<slug:data>', views.furtinures_View, name='furtinuredata'),
    path('applience/', views.houseApplience_view, name='applience'), 
    path('applience/<slug:data>', views.houseApplience_view, name='appliencedata'),
    path('corns/', views.corns_view, name='corns'), 
    path('corns/<slug:data>', views.corns_view, name='cornsdata'),
    path('gas/', views.gas_view, name='gas'), 
    path('gas/<slug:data>', views.gas_view, name='gasdata'),
    path('lumber/', views.lumber_view, name='lumber'), 
    path('lumber/<slug:data>', views.lumber_view, name='lumberdata'),
    path('plastic/', views.plastic_view, name='plastic'), 
    path('plastic/<slug:data>', views.plastic_view, name='plasticdata'),
    path('forest/', views.forest_view, name='forest'), 
    path('forest/<slug:data>', views.forest_view, name='forestdata'),
    path('nautral/', views.natural_view, name='natural'), 
    path('nautral/<slug:data>', views.natural_view, name='naturaldata'),
    path('bandages/', views.bandages_view, name='bandages'), 
    path('bandages/<slug:data>', views.bandages_view, name='bandagesdata'),
    path('injections/', views.injection_view, name='injections'), 
    path('injections/<slug:data>', views.injection_view, name='injectionsdata'),
    path('drops/', views.drops_view, name='drops'), 
    path('drops/<slug:data>', views.drops_view, name='dropsdata'),
    path('ointments/', views.ointments_view, name='ointments'), 
    path('ointments/<slug:data>', views.ointments_view, name='ointmentsdata'),
    path('tablets/', views.tablets_view, name='tablets'), 
    path('tablets/<slug:data>', views.tablets_view, name='tabletsdata'),
    path('syrups/', views.syrups_view, name='syrups'), 
    path('syrups/<slug:data>', views.syrups_view, name='syrupsdata'),
    path('coal/', views.coal_view, name='coal'), 
    path('coal/<slug:data>', views.coal_view, name='coaldata'),
    path('mineral/', views.mineral_view, name='mineral'), 
    path('mineral/<slug:data>', views.mineral_view, name='mineraldata'),
    path('steel/', views.steel_view, name='steel'), 
    path('steel/<slug:data>', views.steel_view, name='steeldata'),
    path('food/', views.food_counter, name='food'),
    path('food/<slug:data>', views.food_counter, name='fooddata'),
    path('hotel/', views.hotel_booking, name='hotel'),
    path('hotel/<slug:data>', views.hotel_booking, name='hoteldata'),
    path('hotel-detail/<int:pk>', views.hotel_service_view, name='hotel-detail'),
    path('hotel-cart/', views.rooms_cart, name='rooms-add-to-cart'),
    path('deletehotel/<slug:pk>', views.room_delete_service, name='deletehotel'),
    path('services/', views.home_services, name='homeservies'),
    path('services-cart/', views.service_cart, name='service-add-to-cart'),
    path('services/<slug:data>', views.home_services, name='servicesdata'),
    path('deleteservice/<slug:pk>', views.delete_service, name='deleteservice'),
    path('services-detail/<int:pk>', views.ServicesDetailsView, name='services-detail'),
    path('railway/', views.railway_view, name='railway'),
    path('train-detail/<int:pk>', views.railway_details_view, name='train-detail'),
    path('train-booked/', views.train_booked, name='train-booked'),
    path('deleteTrain/<slug:pk>', views.delete_train, name='deleteTrain'),    
    path('flight/', views.flight_view, name='flight'),
    path('flight-detail/<int:pk>', views.flight_details_view, name='flight-detail'),
    path('flight-booked/', views.flight_booked, name='flight-booked'),
    path('deleteFlight/<slug:pk>', views.delete_flight, name='deleteFlight'),    
    path('movies/', views.movie_view, name='movies'),
    # path('moviesdata/<slug:data>', views.movie_view, name='moviesdata'),
    path('movie-detail/<int:pk>', views.movie_details_view, name='movie-detail'),
    path('bus/', views.bus_view, name='bus'),
    path('bus-detail/<int:pk>', views.bus_details_view, name='bus-detail'),
    path('bus-booked/', views.bus_booked, name='bus-booked'),
    path('deleteBus/<slug:pk>', views.delete_bus, name='deleteBus'), 
    path('search/', views.search_view, name='search'), 
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
